### ISSUE TITLE
Build Fails on React Native 0.69.3 > Task :react-native-compressor:verifyReleaseResources FAILED

### ISSUE THREAD

**Issue by SMKH-PRO** [numandev1/react-native-compressor#122]
### Current behavior

when I try to create release build, I get following error: 
> Task :react-native-compressor:verifyReleaseResources FAILED
### Platform

- [X] Android
- [] iOS

### React Native Version
0.69.3
### React Native Compressor Version
1.5.2
### Reproducible Steps And Demo
cd android 
./gradlew assembleRelease

**Comment by xchwarze** [comment]
I think this is fixed in 
https://github.com/Shobbak/react-native-compressor/commit/1a53d39bb6f4687332c329811443a6c0568fd256

try install the package from this branch
`yarn add https://github.com/Shobbak/react-native-compressor#cc04c945df1609c3d5773be08aaf975a9ef93b8b`

**Comment by numandev1** [comment]
🙏 sorry for a long ago I was not maintaining due to the huge office workload, hopefully, I am going to start fixing bugs on a weekend basis,
I will fix at least 2 issues on the weekend, for priority bugs you can join the discord channel https://discord.gg/dtYzk8sp where we can discuss which bug is most important

**Comment by numandev1** [comment]
fixed in the latest version, please feel free to reopen if you get any error
