### ISSUE TITLE
iOS not running

### ISSUE THREAD

**Issue by rahuljeevan-experion** [numandev1/react-native-compressor#124]
### Current behavior

Getting this error while trying to run the iOS app.

`SwiftEmitModule normal x86_64 Emitting\ module\ for\ react_native_compressor (in target 'react-native-compressor' from project 'Pods')`

### Platform

- [ ] Android
- [X] iOS

### React Native Version
- 0.69.3

### React Native Compressor Version
- 1.5.2

### Reproducible Steps And Demo

`yarn add react-native-compressor`
`npx pod-install`
`yarn ios`

**NB - issue is happening on M1 mac**

<img width="681" alt="Screenshot 2022-09-27 at 2 28 14 PM" src="https://user-images.githubusercontent.com/90694965/192487266-fd18b968-a076-4aaa-bded-1c820c9cc13c.png">

**Comment by RMuhamar** [comment]
i got same error, any solution ?

**Comment by numandev1** [comment]
🙏 sorry for a long ago I was not maintaining due to the huge office workload, hopefully, I am going to start fixing bugs on a weekend basis,
I will fix at least 2 issues on the weekend, for priority bugs you can join the discord channel https://discord.gg/dtYzk8sp where we can discuss which bug is most important

**Comment by numandev1** [comment]
is anyone test latest version of this package and confirm me if you are getting this or not

**Comment by numandev1** [comment]
fixed in the latest version, please feel free to reopen this issue again if this issue happens again
