### ISSUE TITLE
to slow to compress video

### ISSUE THREAD

**Issue by imadarif** [numandev1/react-native-compressor#125]
### Current behavior
working fine but take to much time to compress the video file.

### Expected behavior
fast

### Platform
Android

### React Native Version
0.68

### React Native Compressor Version
latest.

**Comment by VaibhavValere** [comment]
Facing the same condition on the Android platform specifically. Has any got any workaround for it??

**Comment by numandev1** [comment]
🙏 sorry for a long ago I was not maintaining due to the huge office workload, hopefully, I am going to start fixing bugs on a weekend basis,
I will fix at least 2 issues on the weekend, for priority bugs you can join the discord channel https://discord.gg/dtYzk8sp where we can discuss which bug is most important

**Comment by maydersonmellops** [comment]
Same here

**Comment by leandrosilvaps** [comment]
I have the same problem in android system

**Comment by numandev1** [comment]
fixed in `1.8.2`
