### ISSUE TITLE
SyntaxError unexpected token expected

### ISSUE THREAD

**Issue by arsyrangga** [numandev1/react-native-compressor#138]
![IMG-20221129-WA0031](https://user-images.githubusercontent.com/72026482/204538865-d449e3e5-c69c-473e-99c8-5a902fb89acd.jpg)

Help me

**Comment by numandev1** [comment]
🙏 sorry for a long ago I was not maintaining due to the huge office workload, hopefully, I am going to start fixing bugs on a weekend basis,
I will fix at least 2 issues on the weekend, for priority bugs you can join the discord channel https://discord.gg/dtYzk8sp where we can discuss which bug is most important

**Comment by numandev1** [comment]
you are importing `tsx` file into `js` file, you should import this file from dist folder
