### ISSUE TITLE
TypeError: Cannot read property 'compress' of null

### ISSUE THREAD

**Issue by v1puj** [numandev1/react-native-compressor#142]
I have put the source code of video compressor in my app, but getting TypeError: Cannot read property 'compress' of null and also getting NativeVideoCompressor null. 
Please help me to compress the video

**Comment by gasparnd** [comment]
@v1puj are found any solution? I have the same issue in Android

**Comment by numandev1** [comment]
looks like android linking issue, can you provide reproducable example?

**Comment by numandev1** [comment]
🙏 sorry for a long ago I was not maintaining due to the huge office workload, hopefully, I am going to start fixing bugs on a weekend basis,
I will fix at least 2 issues on the weekend, for priority bugs you can join the discord channel https://discord.gg/dtYzk8sp where we can discuss which bug is most important

**Comment by numandev1** [comment]
fixed in the latest version, please feel free to reopen this issue again if this issue happens again
