### ISSUE TITLE
unable to compress the image Error: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference

### ISSUE THREAD

**Issue by mohdrashidreact** [numandev1/react-native-compressor#145]
### Current behavior
The image is not getting compressed unable to compress the image Error: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
### Expected behavior
The image should be compressed it should not raise any error
### Platform

- [X] Android

### React Native Version
0.69.0

### React Native Compressor Version
1.6.1

### Reproducible Steps And Demo
pass the image uri ..
const result = await ImageCompressor.compress(imageUri, {
            maxWidth: 1000,
            quality: 0.8,
          });
        return result
          }

**Comment by pontustengroth** [comment]
#25 Solved it for me

**Comment by numandev1** [comment]
🙏 sorry for a long ago I was not maintaining due to the huge office workload, hopefully, I am going to start fixing bugs on a weekend basis,
I will fix at least 2 issues on the weekend, for priority bugs you can join the discord channel https://discord.gg/dtYzk8sp where we can discuss which bug is most important

**Comment by numandev1** [comment]
fixed in the latest version, please feel free to reopen if you get any error
