### ISSUE TITLE
Support for React Native 0.71.2?

### ISSUE THREAD

**Issue by ronal2s** [numandev1/react-native-compressor#147]
### Current behavior
Cannot run `pod install` using this library
### Expected behavior
Able to build and use the library like past versions of React Native.
### Platform

- [x] Android 
- [X] iOS

### React Native Version
0.71.2

### React Native Compressor Version
1.6.1

### Reproducible Steps And Demo
1. Use React Native 0.71.2
2. Run ```yarn add react-native-compressor```
3. Run ```pod install``` in iOS folder

**Comment by jarrillaga** [comment]
Any news on this issue? We are facing the same situation and we appreciate your support.

**Comment by numandev1** [comment]
@jarrillaga I tested, and it is working on my side, I am using 0.71.4

**Comment by chaitanyaparashar** [comment]
pod install not working on React native version 0.71.4.

**Comment by numandev1** [comment]
🙏 sorry for a long ago I was not maintaining due to the huge office workload, hopefully, I am going to start fixing bugs on a weekend basis,
I will fix at least 2 issues on the weekend, for priority bugs you can join the discord channel https://discord.gg/dtYzk8sp where we can discuss which bug is most important

**Comment by numandev1** [comment]
fixed in the latest version, please feel free to reopen if you get any error on `0.71.2`
