### ISSUE TITLE
Is this package react native web compatible?

### ISSUE THREAD

**Issue by djaffer** [numandev1/react-native-compressor#148]
Is this package react native web compatible?
Also, does it compress locally or uploads file to compress.

**Comment by numandev1** [comment]
🙏 sorry for a long ago I was not maintaining due to the huge office workload, hopefully, I am going to start fixing bugs on a weekend basis,
I will fix at least 2 issues on the weekend, for priority bugs you can join the discord channel https://discord.gg/dtYzk8sp where we can discuss which bug is most important

**Comment by numandev1** [comment]
@djaffer currently this package, does not support web
