### ISSUE TITLE
cannot read property of "compress" of undefined in react native

### ISSUE THREAD

**Issue by pradhyumansinh9849** [numandev1/react-native-compressor#150]
### Platform

- [X] Android
- [X] iOS

**Comment by yashgada** [comment]
Please share some code here so we can take a look and have better understanding

**Comment by numandev1** [comment]
🙏 sorry for a long ago I was not maintaining due to the huge office workload, hopefully, I am going to start fixing bugs on a weekend basis,
I will fix at least 2 issues on the weekend, for priority bugs you can join the discord channel https://discord.gg/dtYzk8sp where we can discuss which bug is most important

**Comment by numandev1** [comment]
fixed in the latest version, please feel free to reopen this issue again if this issue happens again
