### ISSUE TITLE
When will a new NativeEventEmitter issue handling version be released?

### ISSUE THREAD

**Issue by casicos** [numandev1/react-native-compressor#151]
### Current behavior
 - new NativeEventEmitter()` was called with a non-null argument error in iOS

### Expected behavior
 - np

### Platform 

- [X] Android
- [X] iOS

### React Native Version
- 0.71.4

### React Native Compressor Version
- 1.6.1

### Reproducible Steps And Demo
 - yarn add react-native-compressor
 - cd ios && pod install 
 - cd .. && yarn run ios

**Comment by nnmtesuji** [comment]
I have a same question

**Comment by wezter96** [comment]
Also encountering the same issue.
    Invariant Violation: `new NativeEventEmitter()` requires a non-null argument.

**Comment by numandev1** [comment]
🙏 sorry for a long ago I was not maintaining due to the huge office workload, hopefully, I am going to start fixing bugs on a weekend basis,
I will fix at least 2 issues on the weekend, for priority bugs you can join the discord channel https://discord.gg/dtYzk8sp where we can discuss which bug is most important

**Comment by numandev1** [comment]
fixed in latest version, please free feel to reopen if you get it again
