### ISSUE TITLE
How to generate realpath for audio files

### ISSUE THREAD

**Issue by Karan-Rampal** [numandev1/react-native-compressor#154]
### Current behavior
cannot generate audio compressed path  with the url like: content://com.android.providers.downloads.documents/document/msf%3A1000018002
### Expected behavior
It should compress the audio files, how can I convert this path to : file:///..........
### Platform

- [X] Android
- [X] iOS

### React Native Version
0.70.5
### React Native Compressor Version
1.6.1

**Comment by yashgada** [comment]
Facing the same issue here. Not sure this package manages the content:// uri's which is the future proof way forward.
Can you mention if you found a way around it?

**Comment by numandev1** [comment]
🙏 sorry for a long ago I was not maintaining due to the huge office workload, hopefully, I am going to start fixing bugs on a weekend basis,
I will fix at least 2 issues on the weekend, for priority bugs you can join the discord channel https://discord.gg/dtYzk8sp where we can discuss which bug is most important

**Comment by numandev1** [comment]
@yashgada @Karan-Rampal  fixed in latest version
