### ISSUE TITLE
TypeError: Cannot read property 'compress' of null  in Android 

### ISSUE THREAD

**Issue by isak-sayyed** [numandev1/react-native-compressor#156]
In the function below, I am including all the required parameters:
`Const result = await Image.compress(uri,'maxWidth: 1000, quality: 0.8,'); 
`

but getting TypeError: Cannot read property 'compress' of null in Android

**Comment by rexFX** [comment]
I am using Expo and I had the same issue for Video.

I fixed it by doing:

`npx expo prebuild`
`npx expo run:android`

**Comment by RafaelGusto** [comment]
try putting your options inside an object:

const result = await Image.compress(uri, {
  maxWidth: 1000,
  quality: 0.8,
});

**Comment by numandev1** [comment]
🙏 sorry for a long ago I was not maintaining due to the huge office workload, hopefully, I am going to start fixing bugs on a weekend basis,
I will fix at least 2 issues on the weekend, for priority bugs you can join the discord channel https://discord.gg/dtYzk8sp where we can discuss which bug is most important

**Comment by numandev1** [comment]
fixed in latest version, feel free to reopen if you get it again
