### ISSUE TITLE
compressed video not working on whatsapp

### ISSUE THREAD

**Issue by RafaelGusto** [numandev1/react-native-compressor#158]
i have a chatbot, when i send the video to whatsapp, it doesn't open in the android app, but it opens in whatsApp web.

Android version 13
React Native Version
react-native version 0.66.4

React Native Compressor Version
react-native-compressor 1.6.1

**Comment by yashgada** [comment]
Not sure how this is relevant to this package

**Comment by numandev1** [comment]
🙏 sorry for a long ago I was not maintaining due to the huge office workload, hopefully, I am going to start fixing bugs on a weekend basis,
I will fix at least 2 issues on the weekend, for priority bugs you can join the discord channel https://discord.gg/dtYzk8sp where we can discuss which bug is most important

**Comment by numandev1** [comment]
fixed by https://github.com/numandev1/react-native-compressor/pull/180

**Comment by numandev1** [comment]
fixed in `1.8.2`
