### ISSUE TITLE
TypeError: Cannot read property 'image_compress' of null

### ISSUE THREAD

**Issue by dmi3333** [numandev1/react-native-compressor#165]
Hello!
I have a project in React Native Expo managed. 
I installed react-native-compressor as indicated in the manual, except for 
expo prebuild 
and 
eas build 
because I'm currently using Expo Go. 

However, my application still doesn't recognize the Image component and throws the error 
'Possible Unhandled Promise Rejection (id: 1): TypeError: Cannot read property 'image_compress' of null.' 

What am I doing wrong?

**Comment by ayipzz** [comment]
any solutions?

**Comment by numandev1** [comment]
🙏 sorry for a long ago I was not maintaining due to the huge office workload, hopefully, I am going to start fixing bugs on a weekend basis,
I will fix at least 2 issues on the weekend, for priority bugs you can join the discord channel https://discord.gg/dtYzk8sp where we can discuss which bug is most important

**Comment by numandev1** [comment]
can you try 1.8.5
