### ISSUE TITLE
backgroundUpload: remove misleading docs and exports

### ISSUE THREAD

**Issue by hirbod** [numandev1/react-native-compressor#194]
I noticed that backgroundUpload has options and exports options that aren't passed to or implemented in native at all. My colleague and I spent a couple of hours trying to understand why the upload mode form-data wasn't functioning and why the fieldName support wasn't doing anything. We later realized that much of the code and API seems to have been borrowed from expo-file-system but hasn't been integrated into the native side.

Please remove those to save others the headaches I had. Thank you!

**Comment by numandev1** [comment]
@hirbod I am very very sorry 🙏 🙏 🙏 to face this issue, I added backgroupUpload two years ago and added only the support that my app needed, unfortunately, I cannot drop the backgroupUpload function from this package as many of many users are using this function, I can add full support of backgroupUpload rather than remove it and force all users to migrate, my three to four apps are using backgroupUpload, 

Honestly, I left this package and forgot about backgroupUpload having partial functionality

Again I am very sorry 🙏 to you for this kind of misleading

**Comment by hirbod** [comment]
I didn't mean for you to remove 'backgroundUpload'. Just remove the incorrect types and options that aren't natively supported or implemented. (like uploadType, fileName etc)

**Comment by numandev1** [comment]
fix pushed in `1.8.11`
